# Generated by Django 3.0.4 on 2020-04-03 21:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20200404_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time_created',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 4, 4, 37, 19, 223285)),
        ),
    ]
